package Apps;
import java.util.Iterator;
import Utils.ReducerFunction;

/* Implement Reducer function class for "Count of URL Access Frequency" Application
 * 
 * Count of URL Access Frequency: The map function
 * processes logs of web page requests and outputs
 * hURL, 1i. The reduce function adds together all values
 * for the same URL and emits a hURL, total counti
 * pair.
 */

public class URLCountReducerFunction implements ReducerFunction<String,String> {
	
	/* Function:
	 * Reducer function for "Count of URL Access Frequency" Application
	 * Input:
	 * String Key: URL
	 * String Value: URL count
	 * Output:
	 * Iterator<Map.Entry<String, String>> res: <key,value> pairs generated by value
	 */
	@Override
	 public String call(String s, Iterator<String> it) {
		 int res = 0;
		 while(it.hasNext()) {
			 res += Integer.valueOf(it.next());
		 }
		 return String.valueOf(res);
	 }
}
