package Apps;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import Utils.MapperFunction;

/* Implement Mapper function class for "Count of URL Access Frequency" Application
 * 
 * Count of URL Access Frequency: The map function
 * processes logs of web page requests and outputs
 * hURL, 1i. The reduce function adds together all values
 * for the same URL and emits a hURL, total counti
 * pair.
 */
public class URLCountMapperFunction implements MapperFunction<String, String> {

	/* Function:
	 * Mapper function for "Count of URL Access Frequency" Application
	 * Input:
	 * String Key: Page name
	 * String Value: URL count
	 * Output:
	 * Iterator<Map.Entry<String, String>> res: <key,value> pairs generated by value
	 */
	@Override
	 public Iterator<Map.Entry<String, String>> call(String key, String val) { 
		 List<Map.Entry<String, String>> res = new ArrayList<Map.Entry<String, String>>();
		 
		 res.add(new AbstractMap.SimpleEntry<String, String>(val, "1"));
		 
		 return res.iterator();
	 } 
}
