package Apps;
import java.util.Iterator;
import Utils.ReducerFunction;

/* Implement Reducer function class for "Word Count" Application
 * 
 * Word Count:Consider the problem of counting the number of occurrences
 * of each word in a large collection of documents.
 */

public class WordCountReducerFunction implements ReducerFunction<String,String> {
	
	/* Function:
	 * Reducer function for "Word Count" Application
	 * Input:
	 * String Key: Word
	 * String Value: word count
	 * Output:
	 * Iterator<Map.Entry<String, String>> res: <key,value> pairs generated by value
	 */
	@Override
	 public String call(String s, Iterator<String> it) {
		 int res = 0;
		 while(it.hasNext()) {
			 res += Integer.valueOf(it.next());
		 }
		 return String.valueOf(res);
	 }
}
