package Apps;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import Utils.MapperFunction;

/* Implement Mapper function class for "Word Count" Application
 * 
 * Word Count:Consider the problem of counting the number of occurrences
 * of each word in a large collection of documents.
 */
public class WordCountMapperFunction implements MapperFunction<String, String> {

	/* Function:
	 * Mapper function for "Word Count" Application
	 * Input:
	 * String Key: Document name
	 * String Value: word count
	 * Output:
	 * Iterator<Map.Entry<String, String>> res: <key,value> pairs generated by value
	 */
	@Override
	 public Iterator<Map.Entry<String, String>> call(String key, String val) { 
		 List<Map.Entry<String, String>> res = new ArrayList<Map.Entry<String, String>>();
		 
		 String[] tokens = val.split("\\s+");
		 for(String s : tokens) {
			 res.add(new AbstractMap.SimpleEntry<String, String>(s, "1"));
		 }
		 return res.iterator();
	 } 
}
